[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "f6cb5a80c1e825f1012ed8517d2347e0e6d10642"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "9a66021c0e72111866223d318ad9dc411b8b6183d7d8d42a3c402dd8c4c2ffae"
    url = "https://github.com/EnzymeAD/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.1+1/HelloWorldC.v1.4.1.i686-linux-gnu.tar.xz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "c8aa41cab66118db2387696eba33856344935ce3"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "866db1134e54dbe30eea9ed0897320b5ef6c1684c659d013bfde7ded9759d48e"
    url = "https://github.com/EnzymeAD/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.4.1+1/HelloWorldC.v1.4.1.x86_64-linux-gnu.tar.xz"
